### ISSUE TITLE
Update CodeQL workflow

### ISSUE THREAD

**Issue by daverbk** [daverbk/evolve#20]
The thing to be updated:

```yaml
- name: Perform CodeQL Analysis and Upload SARIF
      id: codeql-analysis
      uses: github/codeql-action/analyze@v3
      with:
        queries: |
          languages/javascript/pointers
          languages/java/pointers
        paths: |
          frontend
          backend
        # Pass the category based on the language being analyzed
        additionalArguments: |
          -D codeql.query.frontend=${{ matrix.language == 'javascript-typescript' }}
          -D codeql.query.backend=${{ matrix.language == 'java-kotlin' }}
```

Additional arguments are probably not required even though we have a frontend and backend folders
